package uscheduler.ui;

import java.util.ArrayList;
import java.util.Collection;
import java.util.TreeSet;


/**
 * Created by psout on 3/9/2016.
 */
public class InternalDataManager {
    private ArrayList<String> openTerms = new ArrayList<>();
    private ArrayList<String> subjects = new ArrayList<>();
    private ArrayList<String> campuses = new ArrayList<>();
    private ArrayList<String> courseNum = new ArrayList<>();
    // USING TREESETS TO ENSURE DUPLICATE ENTRIES DO NOT EXIST WHEN POPULATING THE BELOW LISTS
    private TreeSet<String> sections = new TreeSet<>();
    private TreeSet<String> sessions = new TreeSet<>();
    private TreeSet<String> format = new TreeSet<>();
    private TreeSet<String> instructors = new TreeSet<>();


    private void getTerms(){
        //GoTo OWLExpress and get terms
        openTerms.add("Fall Semester 2016");
        openTerms.add("Summer Semester 2016");
        openTerms.add("Summer Semester 2016");
        openTerms.add("Fall Semester 2015");
        openTerms.add("Summer Semester 2015");
        openTerms.add("Spring Semester 2015");
        openTerms.add("Fall Semester 2014");
        openTerms.add("Summer Semester 2014");
        openTerms.add("Spring Semester 2014");
        openTerms.add("Fall Semester 2013");
        openTerms.add("Summer Semester 2013");
        openTerms.add("Spring Semester 2013");
        openTerms.add("Fall Semester 2012");
        openTerms.add("Summer Semester 2012");
        openTerms.add("Spring Semester 2012");
        openTerms.add("Fall Semester 2011");
        openTerms.add("Summer Semester 2011");
        openTerms.add("Spring Semester 2011");
    }
    private void getSubjectsByTerm(String term) {
        if(term.equals("Fall Semester 2016")) {
            subjects.add("AADS-African Diaspora Studies");
            subjects.add("ACCT-Accounting");
            subjects.add("ACS-Analytics and Data Science");
            subjects.add("ACST-Applied Computer Sci&Tech");
            subjects.add("AMST-American Studies");
            subjects.add("ANTH-Anthropology");
            subjects.add("ARCH-Architecture");
            subjects.add("ARED-Art Education");
            subjects.add("ARH-Art History");
            subjects.add("ART-Art");
            subjects.add("ARTS-Arts");
            subjects.add("ASIA-Asian Studies");
            subjects.add("ATT-Apparel and Textiles");
            subjects.add("BED-Biology Education");
            subjects.add("BIOL-Biology");
            subjects.add("BLAW-Business Law");
            subjects.add("BUSA-Business Administration");
            subjects.add("CE-Civil Engineering");
            subjects.add("CGDD-Computer Game Dsgn&Develm");
            subjects.add("CHED-Chemistry Education");
            subjects.add("CHEM-Chemistry");
            subjects.add("CHNS-Chinese");
            subjects.add("CM-Construction Management");
            subjects.add("COM-Communication");
            subjects.add("COMM-Communication");
            subjects.add("CRJU-Criminal Justice");
            subjects.add("CS-Computer Science");
            subjects.add("CSCH-Coles Scholar");
            subjects.add("CSE-Computer Science Engr");
            subjects.add("CSH - Culinary Sust & Hosp");
            subjects.add("DANC-Dance");
            subjects.add("DWMA-Digtl Writing & Media Art");
            subjects.add("ECE-Early Childhood Education");
            subjects.add("ECET-Electrical&Cmptr Eng Tech");
            subjects.add("ECON-Economics");
            subjects.add("EDAD-Adolescent Education");
            subjects.add("EDCI-Curriculum & Instruction");
            subjects.add("EDG-Engineering Dsgn Graphics");
            subjects.add("EDL-Educational Leadership");
            subjects.add("EDMG-Middle Grades Education");
            subjects.add("EDRD-Education-Reading");
            subjects.add("EDRS-Education-Research");
            subjects.add("EDSM-Secondary & Middle School");
            subjects.add("EDUC-Education");
            subjects.add("EE-Electrical Engineering");
            subjects.add("EHS-Exercise & Health Science");
            subjects.add("ENED-English Education");
            subjects.add("ENGL-English");
            subjects.add("ENGR-Engineering");
            subjects.add("ENGT-Engineering Technology");
            subjects.add("ENTR-Entrepreneurship");
            subjects.add("ENVS-Environmental Science");
            subjects.add("ES-Exercise Science");
            subjects.add("ESL-English as a Second Lang");
            subjects.add("ETEC-Elec Tech in Edu Env");
            subjects.add("EUST-European Studies");
            subjects.add("FILM-Film");
            subjects.add("FIN-Finance");
            subjects.add("FL-Foreign Language");
            subjects.add("FLED-Foreign Language Edu");
            subjects.add("FREN-French");
            subjects.add("FYP-First Yr Pedogogy & Admin");
            subjects.add("GBA-Graduate Business Admin");
            subjects.add("GEOG-Geography");
            subjects.add("GEOL-Geology");
            subjects.add("GIS-Geographic Information Sys");
            subjects.add("GRMN-German");
            subjects.add("GWST-Gender & Women's Studies");
            subjects.add("HEBR-Hebrew");
            subjects.add("HIED-History Education");
            subjects.add("HIST-History");
            subjects.add("HMS-Healthcare Mgmt & Informat");
            subjects.add("HON-Honors Program");
            subjects.add("HPE-Health Promotion & PhysEdu");
            subjects.add("HS-Human Services");
            subjects.add("IEP-Intensive English Program");
            subjects.add("IET-Industrial EngineeringTech");
            subjects.add("ILEC-Leadership, Ethics & Char");
            subjects.add("INCM-Intn'l Conflict Mgmt");
            subjects.add("INED-Inclusive Education");
            subjects.add("INTS-Integrative Studies");
            subjects.add("IPM-International Policy Mgt.");
            subjects.add("IS-Information Systems");
            subjects.add("ISA-Info Security & Assurance");
            subjects.add("ISCI-Integrated Science");
            subjects.add("ISD-Interdisciplinary Studies");
            subjects.add("ISYE-Industrial & System Engr");
            subjects.add("IT-Information Technology");
            subjects.add("ITAL-Italian");
            subjects.add("ITEC-Instructional Technology");
            subjects.add("Info and Comm Technology");
            subjects.add("JPN-Japanese");
            subjects.add("Journalism");
            subjects.add("KOR-Korean");
            subjects.add("KSU-KSU Seminars");
            subjects.add("LALS-Latin American Studies");
            subjects.add("LATN-Latin");
            subjects.add("LDRS-Foundations of Leadership");
            subjects.add("MAED-Math Education");
            subjects.add("MATH-Mathematics");
            subjects.add("ME-Mechanical Engineering");
            subjects.add("MET-Mechanical EngineeringTech");
            subjects.add("MGT-Management");
            subjects.add("MILS-Military Science");
            subjects.add("MKTG-Marketing");
            subjects.add("MSCM-Conflict Management");
            subjects.add("MTRE-Mechatronics Engineering");
            subjects.add("MUAP-Applied Music");
            subjects.add("MUED-Music Education");
            subjects.add("MUSI-Music");
            subjects.add("NURS-Nursing");
            subjects.add("PAD-Public Administration");
            subjects.add("PAX-Peace Studies");
            subjects.add("PHE-Public Health Education");
            subjects.add("PHED - Physics Education");
            subjects.add("PHIL-Philosophy");
            subjects.add("PHYS-Physics");
            subjects.add("POLS-Political Science");
            subjects.add("PORT-Portuguese");
            subjects.add("PR-Public Relations");
            subjects.add("PRWR-Professional Writing");
            subjects.add("PSYC-Psychology");
            subjects.add("QA-Quality Assurance");
            subjects.add("RE-Real Estate");
            subjects.add("REET-Renewable Energy EngrTech");
            subjects.add("RELS-Religion");
            subjects.add("RUSS-Russian");
            subjects.add("SCED-Science Education");
            subjects.add("SCI-Science");
            subjects.add("SM - Sports Management");
            subjects.add("SOCI-Sociology");
            subjects.add("SPAN-Spanish");
            subjects.add("STAT-Statistics");
            subjects.add("STS-Social Issues");
            subjects.add("SURV-Surveying");
            subjects.add("SW-Social Work");
            subjects.add("SWE-Software Engineering");
            subjects.add("SYE-Systems Engineering");
            subjects.add("TCOM-Technical Communication");
            subjects.add("TPS-Theatre & Performance Stud");
            subjects.add("WRIT-Writing");
            subjects.add("Wellness");
        }
    }
    private void getCampusByTerm(String term) {
        if(term.equals("Fall Semester 2016")){
            campuses.add("All");
            campuses.add("Dalton Center");
            campuses.add("eCore");
            campuses.add("Galleria Center");
            campuses.add("Kennesaw Campus");
            campuses.add("KSU Center");
            campuses.add("Marietta Campus");
            campuses.add("Paulding/Dallas Center");
        }
    }
    private void getSectionsByCourse(String subject, String courseNum) {
        sections.clear();
        if(subject.equals("CS-Computer Science") && courseNum.equals("1340")){
            sections.add("02");
            sections.add("05");
            sections.add("08");
            sections.add("11");
            sections.add("22");
            sections.add("32");
            sections.add("11");
            sections.add("08");
            sections.add("02");
        }
        else if(subject.equals("AADS-African Diaspora Studies") && courseNum.equals("2345")){
            sections.add("01");
            sections.add("13");
            sections.add("21");
        }
        else{ sections.add("Classes Not Found"); }
    }
    private void getSessionsByCourse(String subject, String courseNum) {
        sessions.clear();
        if(subject.equals("CS-Computer Science") && courseNum.equals("1340")){
            sessions.add("Full Term");
            sessions.add("Learning Communities");
            sessions.add("Seven Week Session I");
            sessions.add("Seven Week Session II");
            sessions.add("eCore - Eight Week Session I");
            sessions.add("eCore - Eight Week Session II");
            sessions.add("eCore - Full Term");
        }
        else if(subject.equals("AADS-African Diaspora Studies") && courseNum.equals("2345")){
            sessions.add("Full Term");
            sessions.add("Seven Week Session I");
        }
        else{ sessions.add("Classes Not Found"); }
    }
    private void getFormatByCourse(String subject, String courseNum) {
        format.clear();
        if(subject.equals("CS-Computer Science") && courseNum.equals("1340")){
            format.add("Lecture - 100%");
            format.add("Hybrid");
            format.add("Online - 100% Online");
            format.add("Online - 95% Online");
        }
        else if(subject.equals("AADS-African Diaspora Studies") && courseNum.equals("2345")){
            format.add("Lecture - 100%");
            format.add("Hybrid");
        }
        else{ format.add("Classes Not Found"); }
    }
    private void getInstructorsByCourse(String subject, String courseNum) {
        instructors.clear();
        if(subject.equals("CS-Computer Science") && courseNum.equals("1340")) {
            instructors.add("Abbott, Stacey Welsh");
            instructors.add("Abbott-Lyon, Heather L");
            instructors.add("Abernathy, John L");
            instructors.add("Achar, Premila Narayana");
            instructors.add("Ackert, Lucy F");
            instructors.add("Adams, Arnold Frank");
            instructors.add("Adams, Lisa G");
            instructors.add("Adebayo, Akanmu G");
            instructors.add("Adhikari, Dhruba ");
            instructors.add("Adler, Alfred ");
            instructors.add("Aenchbacher, Amy L");
            instructors.add("Akerman, Mary S");
            instructors.add("Akinyemi, Nurudeen ");
            instructors.add("Alamilla, Saul ");
            instructors.add("Albrecht, Eric A");
            instructors.add("Alexander, Christopher W");
            instructors.add("Alexander, Jeffrey W");
            instructors.add("Alford, Lauren Elizabeth");
            instructors.add("Alford, Marcus R");
            instructors.add("Ali, Radwan Mahmoud");
            instructors.add("Allen, Judy A");
            instructors.add("Allison, Audrey Wilson");
            instructors.add("Allman, Samuel David");
            instructors.add("Alme, Karyn A.");
            instructors.add("Amason, Janeen S.");
            instructors.add("Amparan, Bernardo ");
            instructors.add("Anderson, Justin Thomas");
            instructors.add("Anderson, Kami J.");
            instructors.add("Anderson, Kristi Ann");
            instructors.add("Andre Glenn, Rachel ");
            instructors.add("Ao, Yumin ");
            instructors.add("Ariail, Donald ");
            instructors.add("Armer-Giardina, Natashya R");
            instructors.add("Armocida, Rudolph J");
            instructors.add("Armour-Hileman, Victoria L");
            instructors.add("Arnett, Earl Jonathan");
            instructors.add("Artese, Brian P");
            instructors.add("Asgill, Austin B");
            instructors.add("Ashley, Fredrick R");
            instructors.add("Ashley-Thomas, Michelle Renee");
            instructors.add("Askildson, Virginie ");
            instructors.add("Assaad, Farouck K.");
            instructors.add("Atiqullah, Mir ");
            instructors.add("Atkins, Robert W");
            instructors.add("Auldridge, Tammy ");
            instructors.add("Aust, Charles F");
            instructors.add("Aust, Philip J");
            instructors.add("Ayala, Rosana Farias");
            instructors.add("Azriel, Joshua N");
            instructors.add("Babenko, Yuliya V");
            instructors.add("Bacud, Raymond ");
            instructors.add("Bagchi, Aniruddha ");
            instructors.add("Bailey, Bill D.");
            instructors.add("Bailey, Kent L");
            instructors.add("Bailey, Tony Michael");
            instructors.add("Baker, Meredith Beckham");
            instructors.add("Baker, William E");
            instructors.add("Baldwin, Michael ");
            instructors.add("Ball, Thomas R");
            instructors.add("Ballard, Ellen Paige");
            instructors.add("Ballard, John William");
            instructors.add("Ballard, Nancy Medley");
            instructors.add("Bandyopadhyay, Tridib ");
            instructors.add("Barahona-Murphy, Elyse T");
            instructors.add("Barham, Wasim S.");
            instructors.add("Bariteau, Erinn ");
            instructors.add("Barney, Bradley J");
            instructors.add("Barr, Bob ");
            instructors.add("Barrett-Williams, Shannon ");
            instructors.add("Bartlett, Stephen M");
            instructors.add("Barton, Kristin M");
            instructors.add("Baruah, Bharat ");
            instructors.add("Baruah, Subalita ");
            instructors.add("Bass, George Morris");
            instructors.add("Bates, Leslie K");
            instructors.add("Beach, Donna Kay");
            instructors.add("Beach, Michael B");
            instructors.add("Beadles, Sam ");
            instructors.add("Bedette, Kathryn L");
            instructors.add("Beecken, William H");
            instructors.add("Beeks, James W");
            instructors.add("Behrman, Mary D");
            instructors.add("Belegradek, Oleg ");
            instructors.add("Bell, Laura A");
            instructors.add("Bell, Tenisha Taylor");
            instructors.add("Bell, Thomas ");
            instructors.add("Benedict, Jeffrey Martin");
            instructors.add("Benjamin, Jesse J");
            instructors.add("Benson, Debra D.");
            instructors.add("Berman, Jeffrey Lyle");
            instructors.add("Bernal, Barbara Victoria");
            instructors.add("Bernardy, Anja ");
            instructors.add("Berreth, Emily ");
            instructors.add("Berry, Natalie Smith");
            instructors.add("Bertolucci, Craig M");
            instructors.add("Berwald, Olaf ");
            instructors.add("Bessette, Harriet J");
            instructors.add("Bhasin, Tavishi ");
            instructors.add("Bird, Sandra L");
            instructors.add("Birrell, Robert J");
            instructors.add("Blackwell, Leslie J");
            instructors.add("Blackwell, William M");
            instructors.add("Blake, Barbara J");
            instructors.add("Blount, Barry ");
            instructors.add("Blumentritt, Timothy P");
            instructors.add("Bobbie, Patrick O.");
            instructors.add("Bock, Joseph G");
            instructors.add("Boettler, Karen Ann");
            instructors.add("Boettler, Lynn M");
            instructors.add("Bohannon, Jeanne L.");
            instructors.add("Borders, A Leila");
            instructors.add("Botelho, Keith M");
            instructors.add("Bourdeau, Debra G. Taylor");
            instructors.add("Bowden, Martha F");
            instructors.add("Bowers, Cynthia ");
            instructors.add("Boyd, Elizabeth M");
            instructors.add("Boyer, Shelley M");
            instructors.add("Bradburd, Douglas Charles");
            instructors.add("Bradford, John William");
            instructors.add("Branham, Daniel ");
            instructors.add("Brannan, Jane D");
            instructors.add("Brasco, Craig ");
            instructors.add("Brawley, Dorothy E");
            instructors.add("Bray, David E");
            instructors.add("Bremner, Marie N");
            instructors.add("Brennan, Kathleen B");
            instructors.add("Briggs, Constance Margarite");
            instructors.add("Brodak, Molly A.");
            instructors.add("Brooks, John Robert");
            instructors.add("Brookshire, Joy Lynn");
            instructors.add("Broome, Kenneth ");
            instructors.add("Brotherton, Marc A");
            instructors.add("Brotman, Billie A");
        }
        else if(subject.equals("AADS-African Diaspora Studies") && courseNum.equals("2345")){
            instructors.add("Brouthers, Lance E.");
            instructors.add("Brown, Christopher A");
            instructors.add("Brown, Dennis Ted");
            instructors.add("Brown, Patrice S");
            instructors.add("Brown, Robert L");
            instructors.add("Brown, Samuel R");
            instructors.add("Bruns, Justin ");
            instructors.add("Bryan, Charity Leigh");
            instructors.add("Bryantsev, Anton ");
            instructors.add("Bryce, Mark Lee-Anthony");
            instructors.add("Bullins, James S");
            instructors.add("Buonamia, Nicholas ");
            instructors.add("Buonomo, Carolyn F");
            instructors.add("Burch, Anita Perdue");
            instructors.add("Burch, Page ");
            instructors.add("Buresh, Robert J");
            instructors.add("Buresi, Thomas Gérald");
            instructors.add("Burke, Meghan A");
            instructors.add("Burleson, Elizabeth J");
            instructors.add("Burns, David J");
            instructors.add("Burton, Flavia S");
            instructors.add("Burton, Tyra Anne");
            instructors.add("Butcher, Charity D");
            instructors.add("Butler, Renee ");
            instructors.add("Cagle, Mary C");
            instructors.add("Callahan, Brendan E");
            instructors.add("Callahan, Kadian M");
            instructors.add("Calloway, Jimmy ");
            instructors.add("Camargo Dodonova, Dimitri C");
            instructors.add("Campana, Jeffrey C");
            instructors.add("Campbell, Jane E");
            instructors.add("Campbell, Lola Lynne");
            instructors.add("Campbell, Stacy M");
            instructors.add("Cantrell, Kara L.");
            instructors.add("Canty, Jayme ");
            instructors.add("Cao, Zhu ");
            instructors.add("Cardona, Patricia Burrows");
            instructors.add("Cardona, Wilma Enid");
            instructors.add("Carlson, Carolyn S");
            instructors.add("Carpenter, William ");
            instructors.add("Carrico, Gary W");
            instructors.add("Carson, Alfred L");
            instructors.add("Carte, Traci ");
            instructors.add("Carter, Terry ");
            instructors.add("Caylor, Marcus L");
            instructors.add("Chaifetz, Marshal ");
            instructors.add("Chakravarty, Sumit ");
            instructors.add("Chakravorty, Satya S");
            instructors.add("Chamberlain, Sandee M");
            instructors.add("Chambers, Dennis J");
            instructors.add("Chambers, Robert W");
            instructors.add("Chambliss, Charles N");
            instructors.add("Chan, Tak C");
            instructors.add("Chandler, Mary M");
            instructors.add("Chandler, Sandra R");
            instructors.add("Chang, Tom ");
            instructors.add("Chang, Yusun ");
            instructors.add("Chavoshi, Manijeh ");
            instructors.add("Chen, Estella B");
            instructors.add("Cheramie, Robin ");
            instructors.add("Chesarek, Justin R");
            instructors.add("Chesbro, Charles W");
            instructors.add("Chowdhury, Mohammed R");
            instructors.add("Chrestensen, Carol A");
            instructors.add("Chu, James C.");
            instructors.add("Clark, Janet P");
            instructors.add("Clark, Jordyn ");
            instructors.add("Clark, Samantha L");
            instructors.add("Clark, Seth B");
            instructors.add("Clay, Keely ");
            instructors.add("Cleary, William Joseph");
            instructors.add("Cleaveland, Mary Catherine");
            instructors.add("Clements, Alan B");
            instructors.add("Clemons, Jason ");
            instructors.add("Clincy, Victor A.");
            instructors.add("Cobkit, Sutham ");
            instructors.add("Cochran, Justin D");
            instructors.add("Cochrane, La Juana ");
            instructors.add("Cody, John William");
            instructors.add("Coffey, Debra Jean");
            instructors.add("Cole, Judith E.");
            instructors.add("Cole, Mitchell ");
            instructors.add("Colebeck, Donna D.");
            instructors.add("Coleman, Donald A");
            instructors.add("Collard, Carol S");
            instructors.add("Collins, Stephen D.");
            instructors.add("Combs, Jennifer M");
            instructors.add("Como, John D");
            instructors.add("Como, Joseph A.");
            instructors.add("Conrey, Gregory ");
            instructors.add("Constantin, Magdalena ");
            instructors.add("Cook, David L");
            instructors.add("Cooke, Siobhan Alana");
            instructors.add("Corbitt, Anne E");
            instructors.add("Costa, Joseph F");
            instructors.add("Coucheron, Julie ");
            instructors.add("Creasy, Kathleen D");
            instructors.add("Creekmur, Renata ");
            instructors.add("Creel, Sarah R");
            instructors.add("Crews, Sara ");
            instructors.add("Crimm, Lance C");
            instructors.add("Croft, Sheryl Jones");
            instructors.add("Croicu, Ana-Maria ");
            instructors.add("Cross, Ellen D");
            instructors.add("Crotts, Rickie R");
            instructors.add("Crovitz, Darren R");
            instructors.add("Crowder, William S");
            instructors.add("Crump, Kay B");
            instructors.add("Crump, Randall A");
            instructors.add("Cruz-Abazeri, Ana L");
            instructors.add("Cruz-Ortiz, Jaime ");
            instructors.add("Culp, Brian ");
            instructors.add("Dail, Jennifer Suzanne");
            instructors.add("Daly, David Lockridge");
            instructors.add("Daniels, Loretta A");
            instructors.add("Das, Sandip ");
            instructors.add("Davenport, Howard J");
            instructors.add("Davis, Akiko ");
            instructors.add("Davis, Allison C");
            instructors.add("Davis, Bowman O");
            instructors.add("Davis, James ");
            instructors.add("Davis, Laura R.");
            instructors.add("Davis, Marcus C");
            instructors.add("Davis, Patricia ");
            instructors.add("Davis-Cosby, Nicki ");
            instructors.add("Daws, Laura Beth ");
            instructors.add("Deal, Candace Carden");
            instructors.add("de Chesnay, Mary L");
            instructors.add("DeMaio, Joseph David");
            instructors.add("Dembla, Pamila S");
            instructors.add("Deng, Shangrong ");
            instructors.add("Denton, Ann M");
            instructors.add("Derado, Josip ");
            instructors.add("Derenzo, Glynnis Barbara");
            instructors.add("Desrochers, Jr., Robert E");
            instructors.add("Devaney, Thomas F");
            instructors.add("Devereaux, Michelle Dene");
            instructors.add("Devine, Patrick J");
            instructors.add("DeWitt, Jeff R");
            instructors.add("Dias, Michael J");
            instructors.add("Dibble, Valerie A");
            instructors.add("Dickey, Jennifer W.");
            instructors.add("Dillon, Meighan ");
            instructors.add("Diong, Bill M.");
            instructors.add("Diop, Oumar Cherif");
            instructors.add("Dirnberger, Joseph M");
            instructors.add("Dockery, Christopher R");
            instructors.add("Dolan, Drew F.");
            instructors.add("Dollar, Edward Lester");
            instructors.add("Dominick, Joan Elizabe");
            instructors.add("Donahue, Amy K");
            instructors.add("Donovan, Roxanne A");
            instructors.add("Doral, Murat ");
            instructors.add("Doran, David J");
            instructors.add("Doriney, Monica Jeanne");
            instructors.add("Dorman, B Regina");
            instructors.add("Doss, Bridget Anastasia");
            instructors.add("Dover, Paul M");
            instructors.add("Drello, Robert ");
            instructors.add("Dresdner, Andrea Laine");
            instructors.add("Driver, Melissa Kypraios");
            instructors.add("Drought, Wendy Estes");
            instructors.add("Dudenhoeffer, Larrie ");
            instructors.add("Dudenhoeffer, Teresa Alvarez");
            instructors.add("Duff, Jack L");
            instructors.add("Duncan, Jacqueline ");
            instructors.add("Durden, Raquel M");
            instructors.add("Durham, Ralph W");
            instructors.add("Dusza, Erin M");
            instructors.add("Dutcher, Cristen W");
            instructors.add("Duvall, Charles H");
            instructors.add("Dyal, Mari-Amanda A");
            instructors.add("Eakes, Charles E");
            instructors.add("Eanes, Edward ");
            instructors.add("Eaves, Yvonne D");
            instructors.add("Echols, Diana Gilmer");
            instructors.add("Eckford, Alfred Turner");
            instructors.add("Edgerton, Michael T");
            instructors.add("Edwards, Belinda ");
            instructors.add("Edwards, Steven R");
            instructors.add("Eisenberg, Ariel ");
            instructors.add("Eklund, Jason R");
            instructors.add("Elayan, Khalil I");
            instructors.add("El-Itr, Zuhair ");
            instructors.add("Ellermeyer, Sean F");
            instructors.add("Elley, Kristen ");
            instructors.add("Ellis, Jessica A");
            instructors.add("Ellison, Soyia ");
            instructors.add("Emert, Randall A.");
            instructors.add("End-Berg, Lisa Ann");
            instructors.add("Ensign, William E");
            instructors.add("Epps, Kathryn K");
            instructors.add("Eskridge, Dawn Vernida");
            instructors.add("Esmat, Tiffany Ann");
            instructors.add("Estrella, Susanne ");
            instructors.add("Eubanks, Shannon M");
            instructors.add("Evans, Linda S");
            instructors.add("Ewing, Gregory Allen");
            instructors.add("Eybelman, Gene K");
            instructors.add("Ezewudo, Matthew ");
            instructors.add("Fadyn, Joseph N");
            instructors.add("Fallon, Thomas ");
            instructors.add("Fallu, Caroline Marie Louise");
            instructors.add("Fang, Jack C");
            instructors.add("Farfan, Eduardo ");
            instructors.add("Farr, Daniel ");
            instructors.add("Farr Schiller, Angela ");
            instructors.add("Faruque, Abdullah ");
            instructors.add("Fatehi, Kamal ");
            instructors.add("Fazlollah, Alice E");
            instructors.add("Fein, Melvyn L");
            instructors.add("Feito, Yuri ");
            instructors.add("Feng, Amy J");
            instructors.add("Fenton, Peter W");
            instructors.add("Ferguson, Amanda Nicole");
            instructors.add("Ferrani, Ouali A.");
            instructors.add("Ferreira, Daniel R.");
            instructors.add("Figueiredo, Sergio ");
            instructors.add("Figueroa, Neysa O");
            instructors.add("Flower, Bruce W");
            instructors.add("Flowers, Jason A");
            instructors.add("Flythe, Bernard H.");
            instructors.add("Ford, Jason Shaun");
            instructors.add("Ford, Rustavius D");
            instructors.add("Forrester, William R");
            instructors.add("Fortenberry, Kimberly ");
            instructors.add("Fowler, Allan ");
            instructors.add("Fowler, Joel C");
            instructors.add("Fox, Paul Joseph");
            instructors.add("Francis, Kelly A");
            instructors.add("Franke, Volker C.");
            instructors.add("Frankel, Michael ");
            instructors.add("Franklin, Dennis Michael");
            instructors.add("Frederick, Virginia Marie");
            instructors.add("Freeman, Rhonda L");
            instructors.add("Frinzi, Pam ");
            instructors.add("Frisch, Jennifer K");
            instructors.add("Furterer, Sandra L");
            instructors.add("Futch Pollack, Kelly ");
            instructors.add("Gainey, Barbara ");
            instructors.add("Galloway, Linda L");
            instructors.add("Gammill, Rebecca ");
            instructors.add("Gangadharan, Anilkumar K");
            instructors.add("Gannage, George J");
            instructors.add("Ganser, Lisa R");
            instructors.add("Gao, May Hongmei");
            instructors.add("Garcia, Audrey E");
            instructors.add("Gardner, Kimberly D");
            instructors.add("Gardner, Maynard C");
            instructors.add("Garefino, Allison C");
            instructors.add("Garner, Ricky L");
            instructors.add("Garofalo, David ");
            instructors.add("Garrett, Julie E");
            instructors.add("Garrido, Jose M");
            instructors.add("Garziano, Dori R");
            instructors.add("Gayler, Richard A");
            instructors.add("Genetti, Philip ");
            instructors.add("Genetti, II, Philip Anthony");
            instructors.add("Gentile, John S");
            instructors.add("George, Angela A");
            instructors.add("Gephardt, Katarina P");
            instructors.add("Gerda, Monica S");
            instructors.add("Gesick, Richard Alan");
            instructors.add("Ghadge, Ravi ");
            instructors.add("Ghavi, Mahmoud ");
            instructors.add("Gheorghiu, Elena ");
            instructors.add("Gheorghiu-Stephens, Cristina ");
            instructors.add("Ghosh, Dipak K");
            instructors.add("Gibson, Thomas S.");
            instructors.add("Giddens, Elizabeth J.");
            instructors.add("Gildea, Kathleen M");
            instructors.add("Giles, Alexander Lance");
            instructors.add("Gillespie, William L");
            instructors.add("Gilliam, Kenneth P");
            instructors.add("Gillman, Timothy J");
            instructors.add("Gimenez, Marguerite Ottens");
            instructors.add("Gitahi, George ");
            instructors.add("Glassmeyer, David M");
            instructors.add("Glawtschew, Rebecca M");
            instructors.add("Glover, Ebony Monique");
            instructors.add("Gnuse, Robert S.");
            instructors.add("Golan, Maidie R");
            instructors.add("Goldfine, Bernard ");
            instructors.add("Goldman, Benjamin Mark");
            instructors.add("Golubski, Antonio J");
            instructors.add("Goodsite, Michelle Boyd");
            instructors.add("Goodwin, Randall B");
            instructors.add("Gordon, Elizabeth E");
            instructors.add("Goss, Desmond Francis");
            instructors.add("Goss, Ranetta ");
            instructors.add("Grade, Steven ");
            instructors.add("Graf, Karen M");
            instructors.add("Graham, Jerushia L");
            instructors.add("Graham, Roger D");
            instructors.add("Gray, Katherine M.");
            instructors.add("Gray, Kimberly Clark");
            instructors.add("Gray, Thomas E");
            instructors.add("Green, Andrew W");
            instructors.add("Green, Mary D");
            instructors.add("Greenberg, Victoria L");
            instructors.add("Greene, Jeffrey ");
            instructors.add("Gregory, David K");
            instructors.add("Gregory, Diana G");
            instructors.add("Gregory, Sarita M");
            instructors.add("Greil, Rachel H");
            instructors.add("Greipsson, Sigurdur ");
            instructors.add("Griffin, Melanie C");
            instructors.add("Griffin, Roberta T");
            instructors.add("Griffin, William C");
            instructors.add("Griffiths, William ");
            instructors.add("Grindel, Patricia D");
            instructors.add("Grooms, Tony M");
            instructors.add("Grosch, Theodore O.");
            instructors.add("Guglielmi, Luc D");
            instructors.add("Guglielmo, Letizia ");
            instructors.add("Guillory, Nichole A");
            instructors.add("Gulley, Jeremy R");
            instructors.add("Gunther, Melissa ");
            instructors.add("Guo, Rongkai ");
            instructors.add("Gupta, Saurabh ");
            instructors.add("GuramatunhuCooper, Nyasha M");
            instructors.add("Gurkas, Hakki ");
            instructors.add("Gurupatham, Sathish Kumar ");
            instructors.add("Gwaltney, Kevin P");
            instructors.add("Gwirtzman, Daniel ");
            instructors.add("Habers, Natasha Lovelace");
            instructors.add("Hadaway, Nelda H");
            instructors.add("Haimes-Korn, Kim ");
            instructors.add("Hales, Michael Earl");
            instructors.add("Hall, Christopher Lee");
            instructors.add("Hallward, Maia Carter");
            instructors.add("Halstead-Nussloch, R ");
            instructors.add("Ham, Chan H.");
            instructors.add("Hamby, Patsy Ann");
            instructors.add("Hance, Margaret E");
            instructors.add("Hand, Lindsey Jo ");
            instructors.add("Hankey, Leslie Gardner");
            instructors.add("Hanks, Christopher Charles");
            instructors.add("Hardigree, Christian E");
            instructors.add("Hardy, Susan M");
            instructors.add("Hariharan, Govind ");
            instructors.add("Harper, Michael Todd");
            instructors.add("Harris, Gregory Harold");
            instructors.add("Harris, Rochelle L");
            instructors.add("Harrison, Carrin Nichole");
            instructors.add("Harrold, Phillip Maurice");
            instructors.add("Hart, Heather ");
            instructors.add("Hart, Patricia Lynn");
            instructors.add("Hartmangruber, Emily McLean");
            instructors.add("Haseltine, John N");
            instructors.add("Hashas-Degertekin, Mine H.");
            instructors.add("Hatchew, Jeffrey S");
            instructors.add("Hauge, Xueya Y.");
            instructors.add("Hayes, Sherrill W");
            instructors.add("He, Jing Selena");
            instructors.add("Head, Catherine Casey");
            instructors.add("Head, Michelle L");
            instructors.add("Hecht, Brian ");
            instructors.add("Hedeen, Timothy K");
            instructors.add("Heflin, Kristen ");
            instructors.add("Hein, Emily ");
            instructors.add("Heller-Bramblett, Patricia ");
            instructors.add("Helms, Jeffrey L");
            instructors.add("Hendricks, Michael Todd");
            instructors.add("Hendrix, Jerald David");
            instructors.add("Henley, Amy Berry");
            instructors.add("Henricks, Peter L");
            instructors.add("Herbel, Jerry ");
            instructors.add("Herbert, James I");
            instructors.add("Hermanson, Dana R");
            instructors.add("Hermanson, Heather M");
            instructors.add("Herzig, Frances B");
            instructors.add("Hesser, Marcia W.");
            instructors.add("Hewett, Thomas C");
            instructors.add("Hiatt, Mark S.");
            instructors.add("Hicks, Willajoya Carter");
            instructors.add("Hidalgo, Carlos H");
            instructors.add("Hiden, Margaret Hearin");
            instructors.add("Higgins, Jonathan Lee");
            instructors.add("Hightower, Linda A");
            instructors.add("Hill, Gary Jonathan");
            instructors.add("Hill, Mary C");
            instructors.add("Hill, Rebecca ");
            instructors.add("Hillen, Amy F");
            instructors.add("Hinckley, Maria C");
            instructors.add("Ho, Hai T.");
            instructors.add("Hoffmann, Nicolas ");
            instructors.add("Hoganson, Kenneth E");
            instructors.add("Hold, Judith Lynn");
            instructors.add("Holdzkom, Marianne ");
            instructors.add("Holler, Emily K.");
            instructors.add("Holliday, Sarah H.");
            instructors.add("Hollingsworth, Carole L");
            instructors.add("Hollman, Priscilla Johnson");
            instructors.add("Holloway, Eldrige Charles");
            instructors.add("Holman, Karen ");
            instructors.add("Holmes, Sarah Woolverton");
            instructors.add("Holtz, Carol S");
            instructors.add("Honey, Diana K.");
            instructors.add("Hooks, Jerry Dwayne");
            instructors.add("Horton, Donald D");
            instructors.add("Houde, Anita A");
            instructors.add("Housley, Lynne P");
            instructors.add("Howard, Laura W");
            instructors.add("Howard, Theresa M");
            instructors.add("Howes, Pauline A.");
            instructors.add("Howton, Amy D");
            instructors.add("Hoyt, Kristin ");
            instructors.add("Huang, Rongbing ");
            instructors.add("Huang, Xiao ");
            instructors.add("Hudson, Martin L");
            instructors.add("Hughes, Susan Beamon");
            instructors.add("Hung, Chih-Cheng ");
            instructors.add("Hunt, Ruston McClellan");
            instructors.add("Hutcheson, Peggy G");
            instructors.add("Hutchins, Amber L");
            instructors.add("Hutchins, Jennifer ");
            instructors.add("Hutchinson, Deborah A");
            instructors.add("Hutchinson, Matthew John");
            instructors.add("Hutchinson, Richard N");
            instructors.add("Hwang, Kristine Hyejung");
            instructors.add("Hyon, Katherine S");
            instructors.add("Hypolite, Karen Lorraine");
            instructors.add("Ikegwuonu, Patricia A");
            instructors.add("Ilksoy, Erhan ");
            instructors.add("Ingram, Katherine H");
            instructors.add("Ingram, Ulrike K");
            instructors.add("Inman, Kirk ");
            instructors.add("Inman, Michael ");
            instructors.add("Irvin, Matthew W");
            instructors.add("Iscimen, Filyet A");
            instructors.add("Isenhour, John L.");
            instructors.add("Jackson, Charles R");
            instructors.add("Jackson, Kenneth ");
            instructors.add("Jackson, Paula C");
            instructors.add("Jackson, Tyrone M");
            instructors.add("Jafeh, Farzan ");
            instructors.add("Jay, Vickie Sue");
            instructors.add("Jendzurski, Michael ");
            instructors.add("Jenkins, Kalimah ");
            instructors.add("Jenkins, Martha S");
            instructors.add("Jens, Sherri ");
            instructors.add("Ji, Jun ");
            instructors.add("Jimenez, Albert Manuel");
            instructors.add("Jin, Wenhua ");
            instructors.add("Jinks, Kenneth Ryan");
            instructors.add("Joffe, David ");
            instructors.add("Johnson, April A");
            instructors.add("Johnson, Arvin ");
            instructors.add("Johnson, Christopher Harvey");
            instructors.add("Johnson, D. Clint");
            instructors.add("Johnson, David M");
            instructors.add("Johnson, Desirae Kay");
            instructors.add("Johnson, J Gregg");
            instructors.add("Johnson, John David");
            instructors.add("Johnson, Joshua M");
            instructors.add("Johnson, Lisa B");
            instructors.add("Johnson, Ping Hu");
            instructors.add("Johnson, Sarah L.");
            instructors.add("Johnston, Linda M");
            instructors.add("Jolis, Marc Jeffrey");
            instructors.add("Jolley, Dennis Wayne");
            instructors.add("Jones, David E");
            instructors.add("Jones, Holly G");
            instructors.add("Jones, Joan D");
            instructors.add("Jones, Kecia L.");
            instructors.add("Jones, Lee Clayton");
            instructors.add("Jones, Rashaad ");
            instructors.add("Jones, Sandra Hall");
            instructors.add("Jones, Tiffany R");
            instructors.add("Jones, Tonya Craton");
            instructors.add("Jordan, Edward ");
            instructors.add("Jordan, Jeannette ");
            instructors.add("Jordan, Robert Lee");
            instructors.add("Joseph, Lori A");
            instructors.add("Joyce, Pamela L");
            instructors.add("Juneja, Parminder K.");
            instructors.add("Jung, Edward ");
            instructors.add("Jung, Kyung Hun ");
            instructors.add("Jurchenko, Jacqueline Ann");
            instructors.add("Justus, Kayleen ");
            instructors.add("Kalamas, Maria ");
            instructors.add("Kaledin, Martina ");
            instructors.add("Kamasa-Quashie, Cynthia Ann");
            instructors.add("Kane, Victor E");
            instructors.add("Kang, Charles Yang");
            instructors.add("Kang, Lu ");
            instructors.add("Kang, Sunny Y.");
            instructors.add("Karim, Mohammed A.");
            instructors.add("Kathiresan, Kris ");
            instructors.add("Katzman, Brett E.");
            instructors.add("Keating, Kenneth E");
            instructors.add("Kefentse, Darrell ");
            instructors.add("Kehler, David T.");
            instructors.add("Keita, Jennifer A");
            instructors.add("Keith, Melissa Dawn");
            instructors.add("Keleher, Michael ");
            instructors.add("Kelley, Jennifer ");
            instructors.add("Kelley, Susanne Andrea");
            instructors.add("Kelly, Bertram F.");
            instructors.add("Kelso, Charlotte Elizabeth");
            instructors.add("Keltner, Stacy K.");
            instructors.add("Kenney, Michael ");
            instructors.add("Kepler, Maria Alejandra");
            instructors.add("Kerfoot, Cameron Kodiak");
            instructors.add("Kerr, Heather K");
            instructors.add("Kersey, Terrence L");
            instructors.add("Keyser, Robert S.");
            instructors.add("Keyton, Kia Fisher");
            instructors.add("Khalid, Adeel Syed");
            instructors.add("Khan, Freeha Shabnam");
            instructors.add("Khan, Mazida Akhter");
            instructors.add("Khayati, Amine ");
            instructors.add("Khazaei, Ali ");
            instructors.add("Khazaii, Javad ");
            instructors.add("Kidonakis, Nikolaos ");
            instructors.add("Kieran, Rachel A");
            instructors.add("Kim, Bo Kyoung ");
            instructors.add("Kim, Christine Ghia Yee");
            instructors.add("Kim, Heeman ");
            instructors.add("Kim, Taewoo ");
            instructors.add("Kim, Yanghee Anna");
            instructors.add("Kimitei, Symon Kipyagwai");
            instructors.add("King, Adrienne L.");
            instructors.add("King, David Ashley");
            instructors.add("King, Steve H");
            instructors.add("Kinnick, Katherine ");
            instructors.add("Kirby, Vivian G");
            instructors.add("Kirk, Alan B.");
            instructors.add("Kirk, Jeffrey V.");
            instructors.add("Kirk, Nancy Jo");
            instructors.add("Kirsner, Beth ");
            instructors.add("Kirwan, James V");
            instructors.add("Klingler, Lori J");
            instructors.add("Kliszczewicz, Brian M");
            instructors.add("Klym, Kendall ");
            instructors.add("Knapp, Denise R");
            instructors.add("Knudsen, Katherine L.");
            instructors.add("Ko, Grace E");
            instructors.add("Kochman, Ladd M");
            instructors.add("Koepfer Lock, Lisa ");
            instructors.add("Koether, Marina C");
            instructors.add("Kohler, Andreas ");
            instructors.add("Kohler, Debbie M");
            instructors.add("Kokil, Uttam ");
            instructors.add("Kokil, Vinavtee ");
            instructors.add("Kolenko, Thomas A");
            instructors.add("Koltochnik, Lenny J");
            instructors.add("Koppelman, Charles ");
            instructors.add("Kperogi, Farooq A");
            instructors.add("Kraegel, Rebecca Hann");
            instructors.add("Krebs, Elizabeth Ann");
            instructors.add("Kremer, Mark S");
            instructors.add("Kritsch, Kevin ");
            instructors.add("Kuemmerle, Daniel L.");
            instructors.add("Kuhel, Karen A");
            instructors.add("Kulasiri, Ratnappuli ");
            instructors.add("Kushner, Ben F");
            instructors.add("Kuykendal, Dorothy L.");
            instructors.add("Kyle, Mark Evan");
            instructors.add("Lahey, Michael D.");
            instructors.add("Lamle, Keaton K");
            instructors.add("Lance, Julie C");
            instructors.add("Lands, LeeAnn B");
            instructors.add("Laposata, Matthew M");
            instructors.add("Larrotta, Rodney M");
            instructors.add("Larsen, Carolee A.");
            instructors.add("Larsen, Victor ");
            instructors.add("Lartigue, Jonathan W.");
            instructors.add("Laser-Hansen, Kelli Renee");
            instructors.add("Latino, Peter G.");
            instructors.add("Laux, Charles C");
            instructors.add("Laval, June K");
            instructors.add("Laval, Philippe B");
            instructors.add("Lawless, John B");
            instructors.add("Lawson, M. Louise");
            instructors.add("Lebaron, Alan V");
            instructors.add("LeBlanc, Maurice J.");
            instructors.add("Lebron, Tamara ");
            instructors.add("Lee, Gang ");
            instructors.add("Lee, Hoseon ");
            instructors.add("Lee, Jeongyi ");
            instructors.add("LeFebvre, Rebecca Kay");
            instructors.add("Leger, Thierry Alain");
            instructors.add("Legrand, Willy ");
            instructors.add("Leifheit, Jennifer Lynn");
            instructors.add("Lepadatu, Darina ");
            instructors.add("Lepadatu, Gilbert ");
            instructors.add("Lepard, Lisa ");
            instructors.add("Lester, Army ");
            instructors.add("Lester, Deborah H");
            instructors.add("Levy, Aaron ");
            instructors.add("Lewis, Amelia C");
            instructors.add("Lewis, Catherine M");
            instructors.add("Lewis, Matthew Edwin");
            instructors.add("Lewis, Michelle Emerson");
            instructors.add("Li, Lei ");
            instructors.add("Lieberman, Robbie ");
            instructors.add("Liebman, Jesse M");
            instructors.add("Lindsay, Emerson Jay");
            instructors.add("Lindsey, Douglas B");
            instructors.add("Linenberger, Kimberly J");
            instructors.add("Liner, Melissa Corn");
            instructors.add("Link, Tanja C.");
            instructors.add("Liu, Xuepeng ");
            instructors.add("Lo, Dan Chia Tien");
            instructors.add("Loe, Terry W");
            instructors.add("Logan, Monique Cassandra");
            instructors.add("Lombardo, Rick ");
            instructors.add("Long, Amanda Marie");
            instructors.add("Long, John E");
            instructors.add("Loomba, Nidhi ");
            instructors.add("Lord, Katia Caetano");
            instructors.add("Loubiere, Dennis Lee");
            instructors.add("Louten, Jennifer R.");
            instructors.add("Love, Keisha ");
            instructors.add("LoVerde-Dropp, JoAnn M.");
            instructors.add("Lowder, Margaret L.");
            instructors.add("Lowe, Kelley W");
            instructors.add("Lu, Zhongjing ");
            instructors.add("Lubben, Tim J");
            instructors.add("Lundy, Brandon D.");
            instructors.add("Lynn, Kathy Ann");
            instructors.add("Lyons, Linda M");
            instructors.add("Ma, Kuosheng ");
            instructors.add("MacDonald, Leo ");
            instructors.add("Macenczak, Lee Andrew");
            instructors.add("MacQueen, Jennifer L");
            instructors.add("Maddox, Monica Marie");
            instructors.add("Majumder, Sarasij ");
            instructors.add("Makus, Rebecca M");
            instructors.add("Malgeri, Linda M");
            instructors.add("Mallavarapu, Suma ");
            instructors.add("Malluck, John Francis");
            instructors.add("Maloni, Michael J");
            instructors.add("Mandradjieff, Mara ");
            instructors.add("Mangine, Gerald T");
            instructors.add("Manly, Martha B");
            instructors.add("Mann, Betty Acheson Alison ");
            instructors.add("Manning, Marni A");
            instructors.add("Mannion, Richard G.");
            instructors.add("Mao, Xiao Qun");
            instructors.add("March, Connalie Danielson");
            instructors.add("Marchisio, Gaia Laura");
            instructors.add("Marek, Pam ");
            instructors.add("Markle, Gail L");
            instructors.add("Marks, Beth W");
            instructors.add("Marks, John M");
            instructors.add("Marktanner, Marcus ");
            instructors.add("Marquez, Raymundo ");
            instructors.add("Marsh, John D");
            instructors.add("Marshall, Matthew Q.");
            instructors.add("Marshall, Victor B");
            instructors.add("Marsil, Dorothy F");
            instructors.add("Martin, Nicole G");
            instructors.add("Martin, Robert A");
            instructors.add("Martin, Tim ");
            instructors.add("Martinez, David M");
            instructors.add("Martinez, James Michael");
            instructors.add("Mathews, Timothy ");
            instructors.add("Mathisen, Richard E");
            instructors.add("Matthews, Kathy L");
            instructors.add("Mattle, Karl Richard");
            instructors.add("Mattord, Carola Louise");
            instructors.add("Mattord, Herbert J");
            instructors.add("Mauge-Lewis, Carole ");
            instructors.add("Mayeed, Mohammed S.");
            instructors.add("Mayer, Philip D");
            instructors.add("Mayo, Charles M");
            instructors.add("Mazzotta, Stefano ");
            instructors.add("McBrayer, Mary Kay ");
            instructors.add("McCafferty, James T");
            instructors.add("McClane, Leslie C.M");
            instructors.add("McClatchey, Irene S.");
            instructors.add("McClintock, Diana L");
            instructors.add("McComb II, James Marshall");
            instructors.add("McCormick, Caroline Burch");
            instructors.add("McDaniel, Brent Adam");
            instructors.add("McDaniel, Paul N");
            instructors.add("McDonald, James W");
            instructors.add("McElroy, Thomas C");
            instructors.add("McEwan, Scott R");
            instructors.add("McFall, Kevin S.");
            instructors.add("McFarland, Ashley M");
            instructors.add("McGarey, Donald J");
            instructors.add("McGovern, Bryan P");
            instructors.add("McGowan, Bryce L");
            instructors.add("McGrath, Laura ");
            instructors.add("McGrew, Amanda Lynn");
            instructors.add("McIntyre, Ruth S.");
            instructors.add("McKee, Angela K");
            instructors.add("McKelvey, Stephen C");
            instructors.add("McLaughlin, Noah ");
            instructors.add("McLester, Cherilyn Nicole");
            instructors.add("McLester, John R");
            instructors.add("McMahon, Jennifer J.");
            instructors.add("McMahon, Joel ");
            instructors.add("McMorran, Andrew G");
            instructors.add("McMurrain, Wendell G");
            instructors.add("McMurry, Jonathan L");
            instructors.add("McNamara, Corinne L");
            instructors.add("McNeal, Joel R");
            instructors.add("McNeill, Stephen J");
            instructors.add("Meadati, Pavankumar ");
            instructors.add("Meades, Glen D.");
            instructors.add("Meals, Cory DeWitt");
            instructors.add("Meeler, Joseph Lee");
            instructors.add("Melnik, Mikhail ");
            instructors.add("Mendelson, Tobias Matthew");
            instructors.add("Meng, Liuxi ");
            instructors.add("Mervin, Stephen J");
            instructors.add("Mesbahi, Mehrdad ");
            instructors.add("Mesman, Melissa Erin");
            instructors.add("Migliaro, Mary G");
            instructors.add("Miles, Michelle ");
            instructors.add("Milkidis, Stefanos ");
            instructors.add("Miller, Cameron Kenneth");
            instructors.add("Miller, James Stephen");
            instructors.add("Miller, Stephanie K");
            instructors.add("Miller, Susanna Molitoris");
            instructors.add("Miller, Tom W");
            instructors.add("Minear, Jonathan ");
            instructors.add("Mirza, Faisal K");
            instructors.add("Mital, Pratik ");
            instructors.add("Mitchell, David B");
            instructors.add("Mitchell, Jennifer E.");
            instructors.add("Mitchell, Mark B");
            instructors.add("Mitchelson, Matthew L");
            instructors.add("Mojo, Abebe Yitna");
            instructors.add("Monaghan, Marietta ");
            instructors.add("Money, Crystal Nicole");
            instructors.add("Monroe, Tiffany Nicole");
            instructors.add("Montgomery, Robert C.");
            instructors.add("Monti, Thomas ");
            instructors.add("Moodie, Douglas R");
            instructors.add("Moomaw, Ellen W");
            instructors.add("Mooney, Charles D.");
            instructors.add("Moran, John P");
            instructors.add("Moremen, Eileen S");
            instructors.add("Morgan, Amanda Wansa");
            instructors.add("Morgan, Barry ");
            instructors.add("Morgan, David Neilson");
            instructors.add("Morgan, Debbie S.");
            instructors.add("Morgan, Matthew R.");
            instructors.add("Morgan, Nina Y");
            instructors.add("Morris, Douglass B");
            instructors.add("Morris, Michael A");
            instructors.add("Morrissey, Julia ");
            instructors.add("Moses, Oral L");
            instructors.add("Mosholder, Richard S");
            instructors.add("Mosley, Milka M");
            instructors.add("Moss-Bouldin, Shondrika ");
            instructors.add("Moulder, Lisabeth Brown");
            instructors.add("Msimanga, Huggins Z");
            instructors.add("Msimanga, Ntombiyomusa D");
            instructors.add("Muhammad, Toni Yvette");
            instructors.add("Munson, April Simpson");
            instructors.add("Murray, Mary C.");
            instructors.add("Mutchler, Troy R");
            instructors.add("Mutlu, Canan C");
            instructors.add("Myers, Rachel E");
            instructors.add("Nagai, Midori ");
            instructors.add("Naidu, Bhupinder ");
            instructors.add("Napshin, Stuart A.");
            instructors.add("Nasseri, Simin ");
            instructors.add("Neal, Teresa ");
            instructors.add("Negash, Solomon ");
            instructors.add("Negrelli, Kathryn K");
            instructors.add("Neiner, Andrew G");
            instructors.add("Nelms, Tommie Puckett");
            instructors.add("Nelson, Pauline ");
            instructors.add("Neuby, Barbara L");
            instructors.add("Newman, Susan H");
            instructors.add("Newton, June Godshalk");
            instructors.add("Nguyen, Shelbee R");
            instructors.add("Ni, Huan ");
            instructors.add("Ni, Xuelei ");
            instructors.add("Nicholson, William C");
            instructors.add("Niederjohn, Daniel M");
            instructors.add("Niehoff, Viviane V");
            instructors.add("Niemann, Linda G");
            instructors.add("Nijim, Yousef W");
            instructors.add("Nikitin, Keith M");
            instructors.add("Nisley, Thomas ");
            instructors.add("Noiset, Luc P.");
            instructors.add("Noring, Jon E");
            instructors.add("North, Max M");
            instructors.add("North, Sarah M");
            instructors.add("Nowak, Kristine Funkhouser");
            instructors.add("Nowak, Scott J");
            instructors.add("Obeidat, Muhammad A");
            instructors.add("Oberlton, Mia Florence");
            instructors.add("Odeleye, Ayokunle ");
            instructors.add("Odera, Catherine ");
            instructors.add("Odom, Mary Lou");
            instructors.add("Ograbisz, Pamela Herod");
            instructors.add("Oguzmert, Metin ");
            instructors.add("O'Kelley, David McCree");
            instructors.add("Okie, William T");
            instructors.add("Okoye, Chiazam U");
            instructors.add("Okwumabua, Nmadili N");
            instructors.add("Olson, Steven D");
            instructors.add("Omidvar, Iraj ");
            instructors.add("Oncul, Fatih ");
            instructors.add("Onofiok, Otu Steven");
            instructors.add("Orlova-Shokry, Ludmila ");
            instructors.add("Otto, Bobette J");
            instructors.add("Owen, David Samuel");
            instructors.add("Owusu, Robert ");
            instructors.add("Padan, Ruth ");
            instructors.add("Padgett-Harrison, Susan K");
            instructors.add("Padilla, Nathaniel Stephen");
            instructors.add("Page, Daniel William");
            instructors.add("Pallas, Christopher L");
            instructors.add("Palmer, Christopher Collin");
            instructors.add("Palmer, Laura A.");
            instructors.add("Paracka, Daniel Joseph");
            instructors.add("Park, Yoon Hee ");
            instructors.add("Parker, David B");
            instructors.add("Parrott, Charles T");
            instructors.add("Pascu, Nicolae R");
            instructors.add("Pate, Alice K");
            instructors.add("Patrick, Russell ");
            instructors.add("Patrono, Michael F");
            instructors.add("Patterson, Mark W");
            instructors.add("Patterson, Selena ");
            instructors.add("Patton, Randall L");
            instructors.add("Paul, Jomon Alivas");
            instructors.add("Paul, Robert C");
            instructors.add("Payne, Lois Camille");
            instructors.add("Pearcey, Sharon M");
            instructors.add("Pearson, Stephanie L");
            instructors.add("Pede, Tyler Logan");
            instructors.add("Pendergrass, Margaret Baldwin");
            instructors.add("Pepple, Sharon Kay");
            instructors.add("Perrin, Charles ");
            instructors.add("Perrotta, Katherine ");
            instructors.add("Perry, Carolyn C");
            instructors.add("Perry, Michael Wade");
            instructors.add("Peters, Ardith Ann");
            instructors.add("Petersen, Jennifermichele Lyndie");
            instructors.add("Petersen, Kristin M");
            instructors.add("Petersen, Rebecca Dawn");
            instructors.add("Peterson, Allen ");
            instructors.add("Petrillo, Jane A");
            instructors.add("Pettigrew, Justin E");
            instructors.add("Phillips, Jan Readling");
            instructors.add("Piecuch, James R");
            instructors.add("Pieper, Andrew L");
            instructors.add("Pierce, Gerald J");
            instructors.add("Pierce, Jessica ");
            instructors.add("Pierce, Patricia H");
            instructors.add("Pierquet, Sandra L");
            instructors.add("Pincock, Heather ");
            instructors.add("Pires, Alessandra Maria");
            instructors.add("Pittman, Jannie ");
            instructors.add("Pittman, Willie R");
            instructors.add("Pitts, Joshua D");
            instructors.add("Plate, Stephen Wayne");
            instructors.add("Plattner, Andrew S");
            instructors.add("Podchaski, Eric J");
            instructors.add("Pope, Amy Patricia");
            instructors.add("Porter, Kandice M");
            instructors.add("Porter, Tracy Lynn");
            instructors.add("Post, Tiffany Michelle");
            instructors.add("Potter, Jan Cowart");
            instructors.add("Pournaghshband, Hassan ");
            instructors.add("Powell, Sylvia W");
            instructors.add("Powis, Terry G");
            instructors.add("Price, Harry E");
            instructors.add("Price, William E.");
            instructors.add("Pulinkala, Ivan ");
            instructors.add("Pullen, Nancy H");
            instructors.add("Purcell, Jennifer W");
            instructors.add("Pusateri, Thomas P");
            instructors.add("Pynn, Thomas M");
            instructors.add("Qian, Kai ");
            instructors.add("Quatro, Scott A");
            instructors.add("Queen, Trina Marie");
            instructors.add("Quinet, Gregory R");
            instructors.add("Quinones Ortiz, Yoannie Marie");
            instructors.add("Quosigk, Benedikt Markus");
            instructors.add("Rabah, Diana Farhat");
            instructors.add("Raburn, Michael Allen");
            instructors.add("Racel, Masako N.");
            instructors.add("Raczek, Teresa P");
            instructors.add("Ragsdale, Terri S");
            instructors.add("Raines, Susan Summers");
            instructors.add("Ralston-Coley, Kirstin Elizabeth");
            instructors.add("Ramamoorti, Sridhar ");
            instructors.add("Ramaswamy, Honnavally N");
            instructors.add("Ramirez, Gabriel G");
            instructors.add("Ramsey, Donna C");
            instructors.add("Ramsey, Terrence K");
            instructors.add("Ranasinghe, Kisa S.");
            instructors.add("Randall, Christopher K");
            instructors.add("Randolph, Adriane B");
            instructors.add("Rasmusson, Elizabeth M");
            instructors.add("Ratwatte, Manonita ");
            instructors.add("Ravenscraft, David ");
            instructors.add("Ray, Herman E");
            instructors.add("Reese, Scott A");
            instructors.add("Reesor, Victor L");
            instructors.add("Reeve, Kay A");
            instructors.add("Reichert, Nancy ");
            instructors.add("Reid, Susan G");
            instructors.add("Remillard, Joseph H");
            instructors.add("Rendini, Virginia A");
            instructors.add("Rhea, James W");
            instructors.add("Ribeiro, Lucia C");
            instructors.add("Richards, Anne R");
            instructors.add("Richardson, Latrice N");
            instructors.add("Richardson, Ronny ");
            instructors.add("Richey, Amanda B");
            instructors.add("Riddle, John Wesley");
            instructors.add("Riemann, Paul R.");
            instructors.add("Rifkin, Sheldon H.");
            instructors.add("Riley, Judith A.");
            instructors.add("Riley, Steven S");
            instructors.add("Ritter, Laura R");
            instructors.add("Rizzuto, Anthony ");
            instructors.add("Roach, Pamela S");
            instructors.add("Roberts, Allen D.");
            instructors.add("Robertson, Patricia Rogers");
            instructors.add("Robinson, Clarence A");
            instructors.add("Robinson, Karen ");
            instructors.add("Robinson, Laura L");
            instructors.add("Robinson, Rebecca S");
            instructors.add("Robinson-Dooley, Vanessa M");
            instructors.add("Robson, Donald L");
            instructors.add("Rodgers, Charner ");
            instructors.add("Rodriguez, Ricardo ");
            instructors.add("Rodriguez- Schaefer, Darlene X");
            instructors.add("Roebuck, Deborah M");
            instructors.add("Rogers, Daniel T");
            instructors.add("Rogers, Maryan E");
            instructors.add("Ronnenberg, Ryan P");
            instructors.add("Roper, Claudia Viviana");
            instructors.add("Rorabaugh, Peter W.");
            instructors.add("Rose, Israel ");
            instructors.add("Rosenberg, Matthew B");
            instructors.add("Rosengrant, David R");
            instructors.add("Rotnem, Thomas E");
            instructors.add("Rouse, Mary Susan");
            instructors.add("Roy, Abhra ");
            instructors.add("Rudchenko, Tatiana Viktorovna");
            instructors.add("RudeWalker, Mathew ");
            instructors.add("Ruhala, Laura A.");
            instructors.add("Ruhala, Richard J.");
            instructors.add("Rule, Rebecca ");
            instructors.add("Rushton, Tricia Ann");
            instructors.add("Russell, Carl M");
            instructors.add("Russell, Felice A");
            instructors.add("Russell, Lisa M");
            instructors.add("Russell, Phyllis M");
            instructors.add("Russell, Sophia ");
            instructors.add("Rutherfoord, James ");
            instructors.add("Rutherford, Leann Georgia");
            instructors.add("Ryan, Erin Leigh");
            instructors.add("Ryburn, Ligia Xiomara");
            instructors.add("Sachs, Daniel E.");
            instructors.add("Sadeckas, Kenneth A");
            instructors.add("Sadre-Orafai, Jenny R.");
            instructors.add("Saleh, Ali Ibrahim");
            instructors.add("Salman, Muhammad ");
            instructors.add("Salsi, Margaret Lynn");
            instructors.add("Sanchez, Wendy B");
            instructors.add("Sandefur, Amy F.");
            instructors.add("Santini, Federica ");
            instructors.add("Santoro, Hannah Treadway");
            instructors.add("Sarmiento, Maria L");
            instructors.add("Scafidi, Benjamin P");
            instructors.add("Schaad, Scott A");
            instructors.add("Schafer, Brad A");
            instructors.add("Schafer, Jennifer Brooke");
            instructors.add("Schafer, John M");
            instructors.add("Scheck, Lori E");
            instructors.add("Scheier, Sandra ");
            instructors.add("Scherer, Heidi L.");
            instructors.add("Scherrer, Christina Robinson");
            instructors.add("Schill, Vanessa Nichole");
            instructors.add("Schmidt, David Michael");
            instructors.add("Schnur, Alesia M");
            instructors.add("Schofer, Maria A");
            instructors.add("Schramm, Maria Carmen");
            instructors.add("Schreiner, David Blaine");
            instructors.add("Schulzke, Kurt S");
            instructors.add("Schwartz, David M");
            instructors.add("Schwartz, Jesse A");
            instructors.add("Sconzo, Rhonda Penney");
            instructors.add("Scott, Gail ");
            instructors.add("Scott, Heather I");
            instructors.add("Seelarbokus, Chenaz B");
            instructors.add("Selden, Gary L");
            instructors.add("Sen, Debarati ");
            instructors.add("Seo, Youngguk ");
            instructors.add("Serkedakis, Michael G");
            instructors.add("Setiawan, Arief Budi");
            instructors.add("Setzer, Charles B");
            instructors.add("Severson, Marvin J");
            instructors.add("Shade, Sherri Lynne");
            instructors.add("Shahriar, Hossain ");
            instructors.add("Sharma, Vineeta D");
            instructors.add("Shaver, Russell T");
            instructors.add("Shaw, Alan ");
            instructors.add("Shaw, Janet L");
            instructors.add("Shealy, Emmitt H");
            instructors.add("Shelden, Ashley T.");
            instructors.add("Shelley, Robert J");
            instructors.add("Sherer, Robert F");
            instructors.add("Sherr, Laurence E");
            instructors.add("Shi, Xiaohui Rebecca");
            instructors.add("Shi, Yong ");
            instructors.add("Shinholster, Michael Todd");
            instructors.add("Shiver, Kenyon C");
            instructors.add("Shoats, Gary L");
            instructors.add("Shock, David R.");
            instructors.add("Shock, Patti J");
            instructors.add("Shope, James E");
            instructors.add("Shumard, Gordon H");
            instructors.add("Shumate, Shannon ");
            instructors.add("Sichel, Robert S");
            instructors.add("Sichler, Karen Allison");
            instructors.add("Siddiqui, Toazmin ");
            instructors.add("Siha, Samia ");
            instructors.add("Silva, Ernesto P");
            instructors.add("Silverthorn, Bradley S");
            instructors.add("Simon, Robert ");
            instructors.add("Sims, Marlene R.");
            instructors.add("Singh, Rajnish ");
            instructors.add("Sinha, Mona ");
            instructors.add("Sipp, George Cary");
            instructors.add("Sitton, Lara Smith");
            instructors.add("Skelton, Samuel B");
            instructors.add("Skott-Myhre, Hans ");
            instructors.add("Slater-Moody, Judith R");
            instructors.add("Sledd, Erin J.");
            instructors.add("Sligh, Allison C");
            instructors.add("Slinger-Friedman, Vanessa A");
            instructors.add("Slomovitz, Albert I");
            instructors.add("Smallwood, Jennifer Hopkins");
            instructors.add("Smith, Andrew P");
            instructors.add("Smith, Garrett Clark");
            instructors.add("Smith, Herbert ");
            instructors.add("Smith, Hunter Holmes");
            instructors.add("Smith, Jacqueline D");
            instructors.add("Smith, Kathryn T");
            instructors.add("Smith, Keith W");
            instructors.add("Smith, Sabine ");
            instructors.add("Smith, Susan Kirkpatrick");
            instructors.add("Smith, Susan M.E.");
            instructors.add("Smith, Wendy Shae");
            instructors.add("Sneha, Sweta ");
            instructors.add("Snook, Carl D.");
            instructors.add("Soiset, Roger ");
            instructors.add("Soldatenko, Gabriel M");
            instructors.add("Solovjov, Larisa ");
            instructors.add("Sommer, Tomoko Iwai");
            instructors.add("Sooklal, Valmiki K.");
            instructors.add("Sosower, Deborah Linehan");
            instructors.add("Spann, Britta Leigh");
            instructors.add("Spoletini, Paola ");
            instructors.add("Staaf, Christopher ");
            instructors.add("Stabler, David R");
            instructors.add("Stanley, Jonathan Wade");
            instructors.add("Starks, Brian ");
            instructors.add("Steiner, Hillary H");
            instructors.add("Stephens, Edward M");
            instructors.add("Stephenson, Charlotte L");
            instructors.add("Stephenson, Jessica J");
            instructors.add("Stephenson, Sandria ");
            instructors.add("Steppe, Johnathan D.");
            instructors.add("Sterling, Evelina Weidman");
            instructors.add("Stevens, J Larry");
            instructors.add("Stewart, Linda ");
            instructors.add("Stewart, Tracie L");
            instructors.add("Stickel, George W");
            instructors.add("Stockton, James C");
            instructors.add("Stollenz, Michael ");
            instructors.add("Story, Paul ");
            instructors.add("Stout, John D.");
            instructors.add("St. Pierre, Peter E");
            instructors.add("Stricklen, Jean B");
            instructors.add("Stricko, Tara Wynn");
            instructors.add("Stuart, Randy S");
            instructors.add("Sugalski, Mark ");
            instructors.add("Sullivan, Ian Michael");
            instructors.add("Summey, Jennifer F");
            instructors.add("Sumner, Melanie D");
            instructors.add("Suther, Bradley E");
            instructors.add("Sutherland, Erin C.");
            instructors.add("Sutton, Heather D");
            instructors.add("Sutton-Brown-Fox, Camille ");
            instructors.add("Swaim, James Anthony");
            instructors.add("Swain, Brian S");
            instructors.add("Swami, Sita ");
            instructors.add("Sweigart, John ");
            instructors.add("Swint, Christine ");
            instructors.add("Swint, Kerwin C");
            instructors.add("Taglialatela, Jared P");
            instructors.add("Taglialatela, Lauren A");
            instructors.add("Talley, Terri ");
            instructors.add("Tapu, Daniela ");
            instructors.add("Tashchian, Armen ");
            instructors.add("Tatu, David J");
            instructors.add("Tatum, Dawn Celeste");
            instructors.add("Taylor, Gloria A");
            instructors.add("Taylor, Katherine J");
            instructors.add("Terantino, Joseph M");
            instructors.add("Terris, John Joseph");
            instructors.add("Teters, Richard L.");
            instructors.add("Thackston, Michael ");
            instructors.add("Thain, Walter ");
            instructors.add("Thames, Kelly M");
            instructors.add("Thomas, Griselda Denise");
            instructors.add("Thomas, Kimberly Noelle ");
            instructors.add("Thomas, Lawrence Bruce");
            instructors.add("Thomas, Walter ");
            instructors.add("Thompson, Bryan Travis");
            instructors.add("Thompson, David R");
            instructors.add("Thompson, Peter S.");
            instructors.add("Thorne, Charles J");
            instructors.add("Thorsen, Robert Herbert");
            instructors.add("Thrash, Mary K");
            instructors.add("Tippens, Scott Joseph");
            instructors.add("Tis, Laurie L");
            instructors.add("Tompkins, James ");
            instructors.add("Torkornoo, Hope K");
            instructors.add("Toson, Sonia ");
            instructors.add("Totten, Christopher D.");
            instructors.add("Traficante, Debra ");
            instructors.add("Trebits, Robert N");
            instructors.add("Treiber, Linda A");
            instructors.add("Tresham, Harriet ");
            instructors.add("Tsambiras, Joe E");
            instructors.add("Tsay, Bor-Yi ");
            instructors.add("Tseng, Tsai-Tien ");
            instructors.add("Tu, Jun ");
            instructors.add("Tudor, Robert Keith");
            instructors.add("Turchan, Michael ");
            instructors.add("Turner, Nancy ");
            instructors.add("Tutterow, Roger ");
            instructors.add("Usher, Carlton A");
            instructors.add("Vaezi, Seyed Mohammad Reza");
            instructors.add("Valenzuela, Juan Pablo");
            instructors.add("VanBrackle, Lewis N");
            instructors.add("Vandenbussche, Jennifer R.");
            instructors.add("Vande Ven, John C");
            instructors.add("Vande Ven, Susan H");
            instructors.add("Vande Zande, Todd Allen");
            instructors.add("Van Dyke, Michael W");
            instructors.add("VanHeirseele, Catherine Leigh");
            instructors.add("Van Horne, Wayne W");
            instructors.add("Varagona, Lynn Marie");
            instructors.add("Varon, Martin S");
            instructors.add("Vasa-Sideris, Sandra ");
            instructors.add("Vasileva, Ana Markova");
            instructors.add("Vaught, Seneca ");
            instructors.add("Veazie, David R.");
            instructors.add("Veliyath, Rajaram ");
            instructors.add("Venell, Elizabeth ");
            instructors.add("Viakinnou-Brinson, Lucie ");
            instructors.add("Vickrey, Mark ");
            instructors.add("Visscher, Elizabeth Brooks");
            instructors.add("Vlachos, Bernadette L");
            instructors.add("Vladimirov, Katya ");
            instructors.add("Vogelien, Dale L");
            instructors.add("Vona, Bi Roubolo ");
            instructors.add("Voogt, Pieter Gerrit");
            instructors.add("Wachtman, Jeanette M");
            instructors.add("Wade-Berg, Jennifer A");
            instructors.add("Wadsworth, Benjamin K");
            instructors.add("Wagner, Amber Nicole");
            instructors.add("Wagner, Jeff ");
            instructors.add("Wagner, Vanda Doreen");
            instructors.add("Waindi, Isaiah Okoth");
            instructors.add("Wakeling, Victor K");
            instructors.add("Wakeman, Paul R");
            instructors.add("Walker, Richard S");
            instructors.add("Walker, Susan R. Gresham");
            instructors.add("Walkiewicz, Kathryn ");
            instructors.add("Wallsmith, Deborah L");
            instructors.add("Walters, Margaret B");
            instructors.add("Walthour, Bess L");
            instructors.add("Wang, Jin ");
            instructors.add("Wang, Liancheng ");
            instructors.add("Wang, Long (Larry) ");
            instructors.add("Wang, Ying ");
            instructors.add("Wannamaker, George Noell");
            instructors.add("Ward, Amy ");
            instructors.add("Ward, Cameron L.");
            instructors.add("Ward, Chandra Denise");
            instructors.add("Ward, Consuela J");
            instructors.add("Ward, Janet Elizabeth");
            instructors.add("Warren, John A");
            instructors.add("Washington, Lynn M");
            instructors.add("Watson, Stephen James");
            instructors.add("Watson, Steven Craig");
            instructors.add("Watson, Virginia R");
            instructors.add("Watts, Alan P");
            instructors.add("Way, Albert G");
            instructors.add("Way, Irene Holliman");
            instructors.add("Weand, Matthew P");
            instructors.add("Weaver, Betsy F");
            instructors.add("Weaver, Melissa Gayle");
            instructors.add("Weaver, Tiffany M.");
            instructors.add("Webb, Horace Price");
            instructors.add("Wedge, Todd ");
            instructors.add("Weidner, Maureen ");
            instructors.add("Weinstein, Howard J");
            instructors.add("Welch, Scorpio ");
            instructors.add("Weldon-Stephens, Amber Sabrina");
            instructors.add("Weldy, Nina Mace");
            instructors.add("Welker, Christine Anne");
            instructors.add("Wells, Jennifer B");
            instructors.add("Wells, Millicent A.");
            instructors.add("Wermert, James F");
            instructors.add("Wertz, Emma K");
            instructors.add("Wesselink, Brian J");
            instructors.add("West, Pipar Lin");
            instructors.add("Westlund, Erik E");
            instructors.add("White, David P");
            instructors.add("White, Denise C");
            instructors.add("White, Kenneth M");
            instructors.add("White, Mary A");
            instructors.add("White, Stephen A");
            instructors.add("Whitehead, Andrew K");
            instructors.add("Whitlock, Susan B");
            instructors.add("Whitman, Michael E");
            instructors.add("Whittle, Dwayne ");
            instructors.add("Wichman, Yvonne Beard");
            instructors.add("Widmier, Scott ");
            instructors.add("Wikstrom, Jan K");
            instructors.add("Wilcox, Daren R");
            instructors.add("Wiles, Gregory Lynn");
            instructors.add("Wilkinson, Neil Lovett");
            instructors.add("Willard, Jennifer ");
            instructors.add("Williams, Brandi Leigh");
            instructors.add("Williams, Damien Patrick");
            instructors.add("Williams, Darrio H");
            instructors.add("Williams, Donna Jill");
            instructors.add("Williams, Neisha ");
            instructors.add("Williams, Stacey L.");
            instructors.add("Williamson, Adrienne L");
            instructors.add("Williamson, Kenneth M");
            instructors.add("Williamson-Martin, Shannon T");
            instructors.add("Wills, Brian ");
            instructors.add("Wilson, Jeffrey S");
            instructors.add("Wilson, Matthew ");
            instructors.add("Wilson, Ralph T");
            instructors.add("Wilson, Stevie E");
            instructors.add("Winchester, Woodrow W.");
            instructors.add("Winsor, Aubrey Brad");
            instructors.add("Wolfe, Amanda Marie");
            instructors.add("Wolfe, Kathy Gilreath");
            instructors.add("Womack, Deanna F.");
            instructors.add("Wong, Li K");
            instructors.add("Wood, Patricia P");
            instructors.add("Wood, Vallorie N");
            instructors.add("Wood, Virginia S.");
            instructors.add("Woodruff, Dana P");
            instructors.add("Woodruff, Ronna Marie");
            instructors.add("Worthy, Debora A");
            instructors.add("Worthy, Roneisha W.");
            instructors.add("Woszczynski, Amy Burkhalter");
            instructors.add("Wright, Charles W");
            instructors.add("Wu, Tong ");
            instructors.add("Wuertz-Hurley, Stefanie C A");
            instructors.add("Wynn, Charles T");
            instructors.add("Xie, Ying ");
            instructors.add("Yandle, Christopher Harris");
            instructors.add("Yang, Bo ");
            instructors.add("Yang, Jidong ");
            instructors.add("Yang, Ming ");
            instructors.add("Yarde, Cheryl Ann");
            instructors.add("Yee, Tien Mun ");
            instructors.add("Younge, Jasmine E");
            instructors.add("Yun, Soohyun ");
            instructors.add("Zafar, Humayun ");
            instructors.add("Zargouni, Ikbel ");
            instructors.add("Zearfoss, Sean ");
            instructors.add("Zhan, Ginny Q");
            instructors.add("Zhang, Chaohui ");
            instructors.add("Zhang, Chi ");
            instructors.add("Zhang, Jiayan ");
            instructors.add("Zhao, Hong ");
            instructors.add("Zheng, Guangzhi ");
            instructors.add("Zhou, Wei ");
            instructors.add("Zhu, Ying ");
            instructors.add("Zimmer, Katherine E");
            instructors.add("Zimmermann, Ulf");
        }else{ instructors.add("Classes Not Found"); }
    }
    private void getCourseNumBySubject(String subject) {
        courseNum.clear();
        if(subject.equals("CS-Computer Science")){
            courseNum.add("1340");
            courseNum.add("1111");
            courseNum.add("3310");
            courseNum.add("3301");
            courseNum.add("4720");
        }
        else if(subject.equals("AADS-African Diaspora Studies")){
            courseNum.add("1234");
            courseNum.add("2345");
            courseNum.add("9876");
        }else{
            courseNum.add("No Courses found.");
        }
    }
    public ArrayList<String> getOpenTerms(){
        getTerms();
        return openTerms;
    }
    public ArrayList<String> getSubjects(String term){
        getSubjectsByTerm(term);
        return subjects;
    }
    public ArrayList<String> getCampuses(String term){
        getCampusByTerm(term);
        return campuses;
    }
    public Collection<String> getSections(String subject, String courseNum){
        getSectionsByCourse(subject, courseNum);
        return sections;
    }
    public Collection<String> getSessions(String subject, String courseNum){
        getSessionsByCourse(subject, courseNum);
        return sessions;
    }
    public Collection<String> getFormat(String subject, String courseNum){
        getFormatByCourse(subject,courseNum);
        return format;
    }
    public Collection<String> getInstructors(String subject, String courseNum){
        getInstructorsByCourse(subject,courseNum);
        return instructors;
    }
    public ArrayList<String> getCourseNum(String subject){
        getCourseNumBySubject(subject);
        return courseNum;
    }

}
